# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLtDrqYnEuLRbMxCQewKAyEY_GBLoa3V
"""

import streamlit as st
import joblib
import pandas as pd

# Load model and vectorizer
model = joblib.load('model.pkl')
vectorizer = joblib.load('vectorizer.pkl')

# Main function for the Streamlit app
def main():
    st.title("Sentiment Analysis App")

    st.write("Ini adalah aplikasi untuk analisis sentimen.")

    user_input = st.text_area("Masukkan teks untuk analisis sentimen:")
    if st.button("Analisis"):
        input_vector = vectorizer.transform([user_input])
        prediction = model.predict(input_vector)
        sentiment_mapping = {
            0: 'Negatif',
            1: 'Positif',
            2: 'Netral'
        }
        predicted_sentiment_description = sentiment_mapping[prediction[0]]

        # Create a DataFrame to display the results
        results_df = pd.DataFrame({
            'Teks Sentimen': [user_input],
            'Prediksi Sentimen': [predicted_sentiment_description]
        })

        st.write("Hasil Prediksi Sentimen:")
        st.write(results_df)

if __name__ == "__main__":
    main()

