# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLtDrqYnEuLRbMxCQewKAyEY_GBLoa3V
"""

import streamlit as st
import pandas as pd
import joblib
from sklearn.feature_extraction.text import CountVectorizer

# Load model dan vectorizer
model = joblib.load('model.pkl')
vectorizer = joblib.load('vectorizer.pkl')

# Fungsi utama aplikasi
def main():
    st.title("Sentiment Analysis App")

    st.write("Ini adalah aplikasi untuk analisis sentimen.")

    user_input = st.text_area("Masukkan teks untuk analisis sentimen:")
    if st.button("Analisis"):
        input_vector = vectorizer.transform([user_input])
        prediction = model.predict(input_vector)
        st.write(f"Prediksi Sentimen: {'Positif' if prediction[0] == 1 else 'Negatif'}")

if __name__ == "__main__":
    main()